#!/bin/sh
# Generate the Redis ACL file from REDIS_PASSWORD so Redis and the API share a
# single source of truth for the credential (#975). The generated file lives on
# the persisted /data volume and is read by Redis on startup (see aclfile in
# scripts/redis/redis.conf).
#
# The `default` user is what the API authenticates as; the `carbonchain` user is
# an explicit named alias that can later be locked down to a narrower command
# set without touching application config.
set -eu

: "${REDIS_PASSWORD:?REDIS_PASSWORD must be set for the CarbonChain Redis service}"

ACL_FILE=/data/users.acl

umask 077
cat > "$ACL_FILE" <<EOF
# Generated by scripts/redis/redis-entrypoint.sh (#975).
# Do not edit by hand — regenerated from REDIS_PASSWORD on every start.
user default on >${REDIS_PASSWORD} ~* &* +@all
user carbonchain on >${REDIS_PASSWORD} ~* &* +@all
EOF

exec redis-server /usr/local/etc/redis/redis.conf
