[package]
name = "carbonchain-retirement"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "=27.0.6"

[dev-dependencies]
soroban-sdk = { version = "=27.0.6", features = ["testutils"] }
carbonchain-credit-registry = { path = "../credit_registry", features = ["testutils"] }
